version: '3.7'
services:
    app:
        build:
            args:
                user: raulnadasan
                uid: 502
            context: ./
            dockerfile: Dockerfile
        image: gymdemo
        container_name: gymdemo-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - gymdemo
    db:
        image: mysql:8.0
        container_name: gymdemo-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - gymdemo
    nginx:
        image: nginx:1.17-alpine
        container_name: gymdemo-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - gymdemo
networks:
    gymdemo:
        driver: bridge
